OS_MAC="true" when OS is MAC, it was blank before

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -9,15 +9,15 @@
 # outputting anything in those cases.
 if [[ $- != *i* ]]
 then
-    # Shell is non-interactive.  Be done now!
-    return
+  # Shell is non-interactive.  Be done now!
+  return
 fi
 
 # Don't execute commands when match fails
 # shopt -s failglob
 
 OS=$(uname -s)
-OS_MAC=$([[ $OS = *Darwin* ]] && "true" || "false")
+OS_MAC=$([[ $OS = *Darwin* ]] && echo "true" || echo "false")
 
 # overwrite duplicate history
 HISTCONTROL=erasedups:ignorespace
@@ -28,53 +28,53 @@ HISTFILESIZE=12288
 
 if [[ -f ~/.bash_aliases ]]
 then
-    . ~/.bash_aliases
+  . ~/.bash_aliases
 fi
 
 x_running() {
-    # don't check for x in MAC
-    $OS_MAC && return 0;
-    xhost >/dev/null 2>&1 ;
+  # don't check for x in MAC
+  $OS_MAC && return 0;
+  xhost >/dev/null 2>&1 ;
 }
 
 if command -v tmux >/dev/null
 then
-    if tmux has-session >/dev/null 2>&1
-    then
-        # attah only if its not attached
-        [[ -z $TMUX ]] && tmux attach -d \; new-window "bash -c 'cd \"$PWD\"; ${SHELL:=bash}'"
-    else
-        x_running && tmux new
-    fi
+  if tmux has-session >/dev/null 2>&1
+  then
+    # attah only if its not attached
+    [[ -z $TMUX ]] && tmux attach -d \; new-window "bash -c 'cd \"$PWD\"; ${SHELL:=bash}'"
+  else
+    x_running && tmux new
+  fi
 fi
 
 PREV_ORG_PROMPT=""
 
 gen_prompt() {
-    ec="$?"
-    history -a
+  ec="$?"
+  history -a
 
   # kludge !!, as long as it works
   PS1=$(sed 's/^\\e\[41;37;1m [0-9]\+ \\e\[0m//' <<<"$PS1")
 
   if command -v git >/dev/null 2>/dev/null
   then
-      branch="$(git branch --show-current 2>/dev/null)"
+    branch="$(git branch --show-current 2>/dev/null)"
   fi
 
 
   if [[ $USER != "rmnull" ]]
   then
-      user_prefix="\e[31;1m\u\e[0m @ \e[33;1m\h\e[0m"
+    user_prefix="\e[31;1m\u\e[0m @ \e[33;1m\h\e[0m"
   else
-      user_prefix=""
+    user_prefix=""
   fi
 
   ORG_PROMPT="${user_prefix}: \e[47m\e[30m${branch:+${branch}}\e[0m \e[38;5;227m\w\e[0m\n∫ "
 
   if [[ -z $PREV_ORG_PROMPT ]]
   then
-      PREV_ORG_PROMPT=$ORG_PROMPT
+    PREV_ORG_PROMPT=$ORG_PROMPT
   fi
 
   # of course, this assumes other scripts don't make modifications to the
@@ -85,9 +85,9 @@ gen_prompt() {
 
   if [[ $pre_diff -gt 0 ]]
   then
-      PREFIX="${PS1:0:${pre_diff}}"
+    PREFIX="${PS1:0:${pre_diff}}"
   else
-      PREFIX=""
+    PREFIX=""
   fi
 
   SUFFIX="${PS1:$(( ${#PREFIX} + ${#PREV_ORG_PROMPT} ))}"
@@ -97,33 +97,33 @@ gen_prompt() {
   PREV_ORG_PROMPT=${ORG_PROMPT}
 
   if [[ $ec != "0" ]] ; then
-      PS1="\e[41;37;1m $ec \e[0m${PS1}"
+    PS1="\e[41;37;1m $ec \e[0m${PS1}"
   fi
 }
 
 if command -v nvim >/dev/null
 then
-    export EDITOR=nvim
+  export EDITOR=nvim
 fi
 
 if [[ -f ~/.fzf.bash ]]
 then
-    source ~/.fzf.bash
-    FZF_CTRL_T_COMMAND='fd . -0'
-    FZF_CTRL_T_OPTS='--read0'
+  source ~/.fzf.bash
+  FZF_CTRL_T_COMMAND='fd . -0'
+  FZF_CTRL_T_OPTS='--read0'
 fi
 
 if command -v zoxide >/dev/null
 then
-    eval "$(zoxide init bash)"
+  eval "$(zoxide init bash)"
 fi
 
 if ! $OS_MAC
 then
-    if ! x_running
-    then
-        startx
-    fi
+  if ! x_running
+  then
+    startx
+  fi
 fi
 
 ## doesn't overwrite if dir already exists
@@ -131,50 +131,47 @@ mkdir -p "${TMPDIR:-/tmp}"/pids/
 mpdstats_pid_file=""${TMPDIR:-/tmp}"/pids/beet.mpdstats"
 if [[ -f $mpdstats_pid_file ]]
 then
-    pid=$(cat "$mpdstats_pid_file")
-    if ! ps aux | grep "${pid}.*beet mpdstats$" | grep -v grep >/dev/null
-    then
-        rm "$mpdstats_pid_file"
-    fi
+  pid=$(cat "$mpdstats_pid_file")
+  if ! ps aux | grep "${pid}.*beet mpdstats$" | grep -v grep >/dev/null
+  then
+    rm "$mpdstats_pid_file"
+  fi
 fi
 
 if ! [[ -f "$mpdstats_pid_file" ]]
 then
-    if beet mpdstats 2>/dev/null >&2 &
-    then
-        pid="$!"
-        echo -n "$pid" >"$mpdstats_pid_file"
-        disown $pid
-    else
-        echo "failed to start beet mpdstats"
-    fi
+  if beet mpdstats 2>/dev/null >&2 &
+  then
+    pid="$!"
+    echo -n "$pid" >"$mpdstats_pid_file"
+    disown $pid
+  else
+    echo "failed to start beet mpdstats"
+  fi
 fi
 
 
 if [[ -f ~/.config/mpd/pid  ]]; then
-    pid=$(cat ~/.config/mpd/pid)
-    if ! ps aux | grep "${pid}.*mpd$" | grep -v grep >/dev/null; then
-        mpd
-    fi
-else
+  pid=$(cat ~/.config/mpd/pid)
+  if ! ps aux | grep "${pid}.*mpd$" | grep -v grep >/dev/null; then
     mpd
+  fi
+else
+  mpd
 fi > /dev/null 2>/dev/null
 
 
 if [[ -z "$PROMPT_COMMAND" ]]
 then
-    PROMPT_COMMAND=gen_prompt
+  PROMPT_COMMAND=gen_prompt
 else
-    PROMPT_COMMAND="gen_prompt;${PROMPT_COMMAND}"
+  PROMPT_COMMAND="gen_prompt;${PROMPT_COMMAND}"
 fi
 
 # cure for ocd
 bind -x '"\C-l":"tput bel"'
 
-if $OS_MAC
-then
-    export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
-    export TESSDATA_PREFIX="/${HOME}/.local/share/tessdata_best"
-fi
+[[ -x /usr/libexec/java_home ]] && export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
+[[ -f "${HOME}/.local/share/tessdata_best" ]] && export TESSDATA_PREFIX="/${HOME}/.local/share/tessdata_best"
 
 [ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"
