emacs_daemon launch by grepping ps status. Kinda bad but meh it seems to work

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -99,9 +99,9 @@ then
     eval "$(zoxide init bash)"
 fi
 
-## doesn't overwrite if dir already exists
-mkdir -p "${TMPDIR:-/tmp}"/pids/
-mpdstats_pid_file="${TMPDIR:-/tmp}/pids/beet.mpdstats"
+EOS_PIDS_DIR="${TMPDIR:-/tmp}"/pids/
+mkdir -p "$EOS_PIDS_DIR"
+mpdstats_pid_file="${EOS_PIDS_DIR}/beet.mpdstats"
 if [[ -f $mpdstats_pid_file ]]
 then
     pid=$(cat "$mpdstats_pid_file")
@@ -116,9 +116,10 @@ then
         echo -n "$pid" >"$mpdstats_pid_file"
         disown $pid
     else
-        echo "failed to start beet mpdstats"
+        echo "failed to start beet mpdstats" >&2
     fi
 fi
+unset mpdstats_pid_file
 
 if [[ -f ~/.config/mpd/pid  ]]; then
     pid=$(cat ~/.config/mpd/pid)
@@ -172,6 +173,22 @@ then
     . ~/.bash_aliases
 fi
 
+emacs_daemon() {
+    local pid;
+    local server_name="$1";
+    local LOG_FILE="/tmp/emacs_daemon_start.log"
+    [[ -z "$server_name" ]] && return;
+    pid=$(ps aux | grep -F "emacs --daemon=${name}" | grep -v grep | head -n 1)
+
+    if [[ -z "$pid" ]]
+    then
+        emacs --daemon="${name}" >/dev/null 2>&1 &
+        pid=$!
+        #echo -n "$pid" >"$pid_file"
+        disown $pid
+    fi
+}
+
 if command -v emacs >/dev/null 2>/dev/null
 then
     EMACS_DEFAULT_SERVER_NAME="$HOSTNAME"
@@ -179,13 +196,10 @@ then
 
     for name in  "${EMACS_DEFAULT_SERVER_NAME}" # work media learn
     do
-        if ! emacsclient -u -s "$name" -e 't' >/dev/null 2>&1
-        then
-            emacs --daemon="${name}" >/dev/null 2>&1 &
-            disown "$!"
-        fi
+        emacs_daemon "$name"
     done
 fi
+unset emacs_daemon
 
 for editor in "e" "ew" "nvim" "emacs" "vim" "vi"
 do
