formatting changes

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -10,8 +10,8 @@
 # outputting anything in those cases.
 if [[ $- != *i* ]]
 then
-  # Shell is non-interactive.  Be done now!
-  return
+    # Shell is non-interactive.  Be done now!
+    return
 fi
 
 # Don't execute commands when match fails
@@ -29,137 +29,137 @@ HISTFILESIZE=12288
 
 if ! command -v get-current-workspace-name >/dev/null
 then
-  get-current-workspace-name() { :; }
+    get-current-workspace-name() { :; }
 fi
 
 
 x_running() {
-  # don't check for x in MAC
-  $OS_MAC && return 0;
-  if command -v xhost >/dev/null
-  then
-    xhost >/dev/null 2>&1
-  else
-    echo "xhost is not installed, can't detect whether x is running or not." >&2;
-    return 0
-  fi
+    # don't check for x in MAC
+    $OS_MAC && return 0;
+    if command -v xhost >/dev/null
+    then
+        xhost >/dev/null 2>&1
+    else
+        echo "xhost is not installed, can't detect whether x is running or not." >&2;
+        return 0
+    fi
 }
 
 if command -v tmux >/dev/null
 then
-  tnew() {
-    local session_name=""
-    [[ -n "$1" ]] && session_name="-s$1"
-    shift || :
-    tmux new "$@" -n Music "${session_name}" ncmpcpp
-  }
+    tnew() {
+        local session_name=""
+        [[ -n "$1" ]] && session_name="-s$1"
+        shift || :
+        tmux new "$@" -n Music "${session_name}" ncmpcpp
+    }
 
-  tattach() {
-    local sarg=""
-    [[ -n "$1" ]] && sarg="-t${1}"
-    tmux attach-session "${sarg[@]}" -d \; new-window "bash -c 'cd \"$PWD\"; ${SHELL:=bash}'" || tmux attach
-  }
+    tattach() {
+        local sarg=""
+        [[ -n "$1" ]] && sarg="-t${1}"
+        tmux attach-session "${sarg[@]}" -d \; new-window "bash -c 'cd \"$PWD\"; ${SHELL:=bash}'" || tmux attach
+    }
 
-  ws_name=$(get-current-workspace-name | tr '[:upper:]' '[:lower:]')
-  session_name="${ws_name:=eos}"
-  if [[ -z "$SSH_CONNECTION" ]]
-  then
-    if tmux has-session -t "$session_name" >/dev/null 2>&1
+    ws_name=$(get-current-workspace-name | tr '[:upper:]' '[:lower:]')
+    session_name="${ws_name:=eos}"
+    if [[ -z "$SSH_CONNECTION" ]]
     then
-      [[ -z $TMUX ]] && tattach "$session_name"
-    else
-      tnew "$session_name" -d
-      x_running && {
-        tattach "$session_name"
-      }
+        if tmux has-session -t "$session_name" >/dev/null 2>&1
+        then
+            [[ -z $TMUX ]] && tattach "$session_name"
+        else
+            tnew "$session_name" -d
+            x_running && {
+                tattach "$session_name"
+            }
+        fi
     fi
-  fi
 
-  unset session_name
-  unset ws_name
+    unset session_name
+    unset ws_name
 fi
 
 PREV_ORG_PROMPT=""
 
 gen_prompt() {
-  ec="$?"
-  history -a
+    ec="$?"
+    history -a
 
-  # kludge !!, as long as it works
-  PS1=$(echo -n "$PS1" | sed 's/^\\e\[41;37;1m [0-9][0-9]* \\e\[0m//')
+    # kludge !!, as long as it works
+    PS1=$(echo -n "$PS1" | sed 's/^\\e\[41;37;1m [0-9][0-9]* \\e\[0m//')
 
-  if command -v git >/dev/null 2>/dev/null
-  then
-    branch="$(git branch --show-current 2>/dev/null)"
-  fi
+    if command -v git >/dev/null 2>/dev/null
+    then
+        branch="$(git branch --show-current 2>/dev/null)"
+    fi
 
-  if [[ "$USER" != "rmnull" ]] || [[ -n "$SSH_CONNECTION" ]]
-  then
-    user_prefix="\e[31;1m\u\e[0m @ \e[33;1m\h\e[0m"
-  else
-    user_prefix=""
-  fi
+    if [[ "$USER" != "rmnull" ]] || [[ -n "$SSH_CONNECTION" ]]
+    then
+        user_prefix="\e[31;1m\u\e[0m @ \e[33;1m\h\e[0m"
+    else
+        user_prefix=""
+    fi
 
-  hints=""
-  if [[ -n $HOMEBREW_DEVELOPER ]]
-  then
-    hints+="\e[1;33m🍺\e[;0m"
-  fi
+    hints=""
+    if [[ -n $HOMEBREW_DEVELOPER ]]
+    then
+        hints+="\e[1;33m🍺\e[;0m"
+    fi
 
-  ORG_PROMPT="${user_prefix}: \e[47m\e[30m${branch:+${branch}}\e[0m ${hints} \e[38;5;227m\w\e[0m\n∫ "
+    ORG_PROMPT="${user_prefix}: \e[47m\e[30m${branch:+${branch}}\e[0m ${hints} \e[38;5;227m\w\e[0m\n∫ "
 
-  if [[ -z $PREV_ORG_PROMPT ]]
-  then
-    PREV_ORG_PROMPT=$ORG_PROMPT
-  fi
+    if [[ -z $PREV_ORG_PROMPT ]]
+    then
+        PREV_ORG_PROMPT=$ORG_PROMPT
+    fi
 
-  # of course, this assumes other scripts don't make modifications to the
-  # in the middle of PS1
-  # dont overwrite prompt generated by other scripts
-  # other scripts may have added additional info the prompt
-  pre_diff="$(( ${#PS1} - ${#PREV_ORG_PROMPT} ))"
+    # of course, this assumes other scripts don't make modifications to the
+    # in the middle of PS1
+    # dont overwrite prompt generated by other scripts
+    # other scripts may have added additional info the prompt
+    pre_diff="$(( ${#PS1} - ${#PREV_ORG_PROMPT} ))"
 
-  if [[ $pre_diff -gt 0 ]]
-  then
-    PREFIX="${PS1:0:${pre_diff}}"
-  else
-    PREFIX=""
-  fi
+    if [[ $pre_diff -gt 0 ]]
+    then
+        PREFIX="${PS1:0:${pre_diff}}"
+    else
+        PREFIX=""
+    fi
 
-  SUFFIX="${PS1:$(( ${#PREFIX} + ${#PREV_ORG_PROMPT} ))}"
+    SUFFIX="${PS1:$(( ${#PREFIX} + ${#PREV_ORG_PROMPT} ))}"
 
 
-  PS1="${PREFIX}${ORG_PROMPT}${SUFFIX}"
-  PREV_ORG_PROMPT=${ORG_PROMPT}
+    PS1="${PREFIX}${ORG_PROMPT}${SUFFIX}"
+    PREV_ORG_PROMPT=${ORG_PROMPT}
 
-  if [[ $ec != "0" ]] ; then
-    PS1="\e[41;37;1m $ec \e[0m${PS1}"
-  fi
+    if [[ $ec != "0" ]] ; then
+        PS1="\e[41;37;1m $ec \e[0m${PS1}"
+    fi
 }
 
 if command -v nvim >/dev/null
 then
-  export EDITOR=nvim
+    export EDITOR=nvim
 fi
 
 if [[ -f ~/.fzf.bash ]]
 then
-  source ~/.fzf.bash
-  export FZF_CTRL_T_COMMAND='fd . -0'
-  export FZF_CTRL_T_OPTS='--read0'
+    source ~/.fzf.bash
+    export FZF_CTRL_T_COMMAND='fd . -0'
+    export FZF_CTRL_T_OPTS='--read0'
 fi
 
 if command -v zoxide >/dev/null
 then
-  eval "$(zoxide init bash)"
+    eval "$(zoxide init bash)"
 fi
 
 if ! $OS_MAC
 then
-  if ! x_running  && [[ -z "$SSH_CONNECTION" ]]
-  then
-    startx
-  fi
+    if ! x_running  && [[ -z "$SSH_CONNECTION" ]]
+    then
+        startx
+    fi
 fi
 
 ## doesn't overwrite if dir already exists
@@ -167,34 +167,34 @@ mkdir -p "${TMPDIR:-/tmp}"/pids/
 mpdstats_pid_file="${TMPDIR:-/tmp}/pids/beet.mpdstats"
 if [[ -f $mpdstats_pid_file ]]
 then
-  pid=$(cat "$mpdstats_pid_file")
-  kill -s 0 "$pid" 2>/dev/null || rm "$mpdstats_pid_file"
+    pid=$(cat "$mpdstats_pid_file")
+    kill -s 0 "$pid" 2>/dev/null || rm "$mpdstats_pid_file"
 fi
 
 if ! [[ -f "$mpdstats_pid_file" ]]
 then
-  if beet mpdstats 2>/dev/null >&2 &
-  then
-    pid="$!"
-    echo -n "$pid" >"$mpdstats_pid_file"
-    disown $pid
-  else
-    echo "failed to start beet mpdstats"
-  fi
+    if beet mpdstats 2>/dev/null >&2 &
+    then
+        pid="$!"
+        echo -n "$pid" >"$mpdstats_pid_file"
+        disown $pid
+    else
+        echo "failed to start beet mpdstats"
+    fi
 fi
 
 if [[ -f ~/.config/mpd/pid  ]]; then
-  pid=$(cat ~/.config/mpd/pid)
-  kill -s 0 "$pid" 2>/dev/null || mpd
+    pid=$(cat ~/.config/mpd/pid)
+    kill -s 0 "$pid" 2>/dev/null || mpd
 else
-  mpd
+    mpd
 fi > /dev/null 2>/dev/null
 
 if [[ -z "$PROMPT_COMMAND" ]]
 then
-  PROMPT_COMMAND=gen_prompt
+    PROMPT_COMMAND=gen_prompt
 else
-  PROMPT_COMMAND="gen_prompt;${PROMPT_COMMAND}"
+    PROMPT_COMMAND="gen_prompt;${PROMPT_COMMAND}"
 fi
 
 # [[ -x /usr/libexec/java_home ]] && JAVA_HOME=$(/usr/libexec/java_home -v 1.8) && export JAVA_HOME
@@ -204,13 +204,13 @@ fi
 
 if command -v ssh-add >/dev/null && ! ssh-add -l >/dev/null 2>&1
 then
-  ssh-add -k ~/.ssh/pi.key
+    ssh-add -k ~/.ssh/pi.key
 fi
 
 if [[ -e "$HOME"/.asdf ]]
 then
-  . "$HOME"/.asdf/asdf.sh
-  . "$HOME"/.asdf/completions/asdf.bash
+    . "$HOME"/.asdf/asdf.sh
+    . "$HOME"/.asdf/completions/asdf.bash
 fi
 
 if command -v emacs >/dev/null 2>/dev/null
@@ -231,5 +231,23 @@ fi
 
 if [[ -f ~/.bash_aliases ]]
 then
-  . ~/.bash_aliases
+    . ~/.bash_aliases
 fi
+
+## conda init startup times are slow, and i don't use it often
+conda_shell() {
+    # >>> conda initialize >>>
+    # !! Contents within this block are managed by 'conda init' !!
+    __conda_setup="$('/home/rmnull/af/conda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
+    if [ $? -eq 0 ]; then
+        eval "$__conda_setup"
+    else
+        if [ -f "/home/rmnull/af/conda3/etc/profile.d/conda.sh" ]; then
+            . "/home/rmnull/af/conda3/etc/profile.d/conda.sh"
+        else
+            export PATH="/home/rmnull/af/conda3/bin:$PATH"
+        fi
+    fi
+    unset __conda_setup
+    # <<< conda initialize <<<
+}
